GET http://localhost:8000/products/ HTTP/1.1

###

GET http://localhost:8000/products/2/ HTTP/1.1

###

PUT http://localhost:8000/products/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NjYwODUwLCJpYXQiOjE3NzQ2NjA1NTAsImp0aSI6ImFmZjdmMzQ4ZjI5YTQ5ZmI5ZjViN2NiMjM2NTVmNmExIiwidXNlcl9pZCI6IjEifQ.rkELEmP1QTIt6IUmu5eY31N9ZJNFBNmbWQlX6FcCSBU


{
  "name": "A test tv",
  "description": "Maiores reiciendis quos voluptates consequatur blanditiis labore commodi facere tempora, sapiente nemo ducimus laudantium quia, excepturi perferendis facere nobis aperiam eius ipsam, itaque necessitatibus ipsa incidunt porro quis eum ducimus soluta non? Maxime maiores aspernatur vel tenetur, doloremque quas sunt rem sint minima accusantium exercitationem, ipsa quae consequatur laboriosam debitis?",
  "price": "12",
  "stock": 4
}

###

DELETE http://localhost:8000/products/1/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NjYwODUwLCJpYXQiOjE3NzQ2NjA1NTAsImp0aSI6ImFmZjdmMzQ4ZjI5YTQ5ZmI5ZjViN2NiMjM2NTVmNmExIiwidXNlcl9pZCI6IjEifQ.rkELEmP1QTIt6IUmu5eY31N9ZJNFBNmbWQlX6FcCSBU

###

POST  http://localhost:8000/products/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NTcyODg5LCJpYXQiOjE3NzQ1NzI1ODksImp0aSI6ImQ4MGUzNWZjMTMzODQ0ZDI4YmVmYTFhMWNlNGE5ZTgxIiwidXNlcl9pZCI6IjEifQ.92gcOdroOljzIN7mW1cXHQFBf6YhWL_C1iB3n25q6p0

{
    "name":"TV",
    "price":300.00,
    "stock":14,
    "description": "amazing Tv"
}

###

POST  http://localhost:8000/api/token/  HTTP/1.1
Content-Type: application/json

{
    "username":"admin",
    "password":"test"
}


###

POST  http://localhost:8000/api/token/refresh/  HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc3NDc0MzI3OSwiaWF0IjoxNzc0NjU2ODc5LCJqdGkiOiI2MzRlMjA2ZTQzNDQ0YzU1YTU2M2VhYzI4OGRmMWRkYyIsInVzZXJfaWQiOiIxIn0.8H62BREOxlMwLS9_0UpB62V6X_Y1IkBfhrk3U_WH0CM"
}

###

GET  http://localhost:8000/user-orders/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc0NTcyOTMxLCJpYXQiOjE3NzQ1NzI2MzEsImp0aSI6IjliMWM5MjVhOTA3ZDRmYTY4OThhYjdjOTdjMmUwMjQ3IiwidXNlcl9pZCI6IjIifQ.aqB4tQ8lTD5_59b8pizH1IF5yfVHoEUmJUhVLCGhMi4

###

GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NDU3ODI1LCJpYXQiOjE3NzY0NTc1MjUsImp0aSI6IjM2YTNlZjBjZTZhOTQ2NTRiZGRmNDcxMjYwOTg2ZGUyIiwidXNlcl9pZCI6IjEifQ.v2s7Wcq0kkcB2TdEGN2jKbWYO3y8n4HlLDG-RsRif-Y

###

GET http://localhost:8000/orders/f483478e-6c12-4ea6-bd83-8eab429a195d  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MDQ1NTI5LCJpYXQiOjE3NzYwNDUyMjksImp0aSI6IjY3ZmIzOWI2MDJiZDQxZWY4MDZjYzhkMzY5NTY3MDZmIiwidXNlcl9pZCI6IjIifQ.W-DNI_7ogeIP50EVBt1HRX71a8OGWQYuGrTDtcOt30A

###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2NDk0ODEwLCJpYXQiOjE3NzY0OTEyMTAsImp0aSI6ImQ1ZmU3ODI2ZTVmNjRiNzZhMWQyYTEzMzNiOWQ2MTY1IiwidXNlcl9pZCI6IjEifQ.Noe6VuVnY9SEBuedBUCI3ywmtcM2e2C86llsNhDYijs

{
  "status": "Pending",
  "items": [
    {
      "product": 2,
      "quantity": 2
    },
    {
        "product": 3,
        "quantity": 1
    }
  ]
}

###

PUT http://localhost:8000/orders/f483478e-6c12-4ea6-bd83-8eab429a195d/  HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MDk3Njg5LCJpYXQiOjE3NzYwOTczODksImp0aSI6IjMyNGM3MTQzOWVhODQ5OGU5YWM5NGY2NTBlNDZjOTNkIiwidXNlcl9pZCI6IjIifQ.xqcijC6Dc7KG2mEcBELeootX2dnCd-Dx0PKVNP0ApdE

{
  "status": "Pending",
  "items": [
    {
      "product": 2,
      "quantity": 3
    },
    {
        "product": 3,
        "quantity": 1
    }
  ]
}

###

DELETE http://localhost:8000/orders/f483478e-6c12-4ea6-bd83-8eab429a195d/  HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzc2MDk4ODQ2LCJpYXQiOjE3NzYwOTg1NDYsImp0aSI6IjdiNzlmZTc3OTdiOTQzMjg4ZGZmNzUxMzZlN2NlYTA1IiwidXNlcl9pZCI6IjIifQ.vj0dYZUiv0GCJHO_332xhX_PvrM8asZmogi9aZ2rA8I
